### ISSUE TITLE
调用爆破功能时报错，没有传入端口

### ISSUE THREAD

**Issue by wxi3** [1c3z/ARL-NPoC#17]
命令：brute -t 127.0.0.1 -n MysqlBrute
报错：
[2024-02-06 18:59:26] [WARNING] [MainThread] [BasePlugin.py:167] [MysqlBrute] mysql://127.0.0.1 an integer is required (got type NoneType) 
[2024-02-06 18:59:26] [ERROR] [MainThread] [BasePlugin.py:172] an integer is required (got type NoneType)
Traceback (most recent call last):
  File "/Users/leisure/Documents/py-code/vue-admin-template/api/xing/core/BasePlugin.py", line 157, in run
    return do_action()
  File "/Users/leisure/Documents/py-code/vue-admin-template/api/xing/core/BasePlugin.py", line 74, in do_brute
    if not self.check_app(target=self.target):
  File "/Users/leisure/Documents/py-code/vue-admin-template/api/xing/plugins/brute/MysqlBrute.py", line 43, in check_app
    client = self.conn_target()
  File "/Users/leisure/Documents/py-code/vue-admin-template/api/xing/core/BasePlugin.py", line 203, in conn_target
    client.connect((host, port))
TypeError: an integer is required (got type NoneType)
通过调试定位到函数：
    def conn_target(self, timeout=4):
        """
        连接到目标, 请调用后一定要手动close
        """

        host = self.target_info["host"]
        port = self.target_info["port"]
        client = socket.socket()
        client.settimeout(timeout)
        client.connect((host, port))

        return client
程序走到port = self.target_info["port"]时，返回的是None

**Comment by wxi3** [comment]
谢谢你的回答，但是貌似还有一个问题，就是我将我本地的mysql密码改为123456时，并没有爆破出来：
[2024-02-06 19:41:34] [INFO] [MainThread] [main.py:167] load plugin 1 
[2024-02-06 19:41:34] [INFO] [MainThread] [PluginRunner.py:33] [1/1] PluginRunner MysqlBrute
[2024-02-06 19:41:34] [INFO] [MainThread] [BasePlugin.py:73] start brute mysql mysql://127.0.0.1:3306
[2024-02-06 19:41:34] [INFO] [MainThread] [BasePlugin.py:77] found mysql mysql://127.0.0.1:3306
[2024-02-06 19:41:34] [INFO] [MainThread] [BasePlugin.py:80] load auth pair 76

**Comment by wxi3** [comment]
Mysql数据库爆破测试，发现即使是正确密码，result依然返回None，是不是因为不支持8.0的数据库啊

**Comment by 1c3z** [comment]
可能。快过年了🧨，多陪陪家人👪吧
